---
# This Docker composition file is used to build and test the container

name: skeleton-docker

secrets:
  aws_config:
    file: ./src/secrets/aws_config
  database_creds:
    file: ./src/secrets/database_creds.yml

services:
  trustymail_reporter:
    # Run the container normally
    build:
      context: .
      dockerfile: Dockerfile
<<<<<<< HEAD:docker-compose.yml
    depends_on:
      - redis
    image: cisagov/trustymail_reporter
    init: true
    restart: "no"
<<<<<<< HEAD
=======
=======
>>>>>>> eafe720594319b9503bd5e6d7e5b59e61ff9d6d5:compose.yml
    environment:
      - ECHO_MESSAGE=Hello World from docker compose!
    image: cisagov/example
    init: true
    ports:
      - mode: host
        protocol: tcp
<<<<<<< HEAD:docker-compose.yml
        mode: host
>>>>>>> 0d48ebd47a28a887868ea3093e675e95f3843561
    secrets:
      - source: aws_config
        target: aws_config
      - source: database_creds
        target: database_creds.yml
  redis:
    image: redis:alpine
=======
        published: "8421"
        target: 8421
    restart: "no"
    secrets:
      - source: quote_txt
        target: quote.txt

  example-version:
    # Run the container to collect version information
    command: --version
    image: cisagov/example
    init: true
    restart: "no"
>>>>>>> eafe720594319b9503bd5e6d7e5b59e61ff9d6d5:compose.yml
